[[multipath.switch]]
name="?"
[multipath.switch.ssh]
ip="?"
port="?"
user="?"
password="?"

[multipath.switch.bmv2]
port="?"
register_indexes=[2,3,4]


[[multipath.switch]]
name="?"
[multipath.switch.ssh]
ip="?"
port="?"
user="?"
password="?"

[multipath.switch.bmv2]
port="?"
register_indexes=[4,3,2]