[multipath.iperf]
interval=1#秒
port=5000

[multipath.ddqn]
interval=4#秒

[[multipath.switch]]
name="188"
[multipath.switch.ssh]
ip="?"
port="6188"
user='?'
password="?"

[multipath.switch.bmv2]
port="9091"
register_indexes=[4,3,2]


[[multipath.switch]]
name="182"
[multipath.switch.ssh]
ip="?"
port="6182"
user='?'
password="?"

[multipath.switch.bmv2]
port="9091"
register_indexes=[2,3,4]